import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
        textTheme: ThemeData.dark().textTheme.apply(
          fontFamily: 'Pretendard',
        ),
      ),
      home: Scaffold(
        body: ListView(
          children: const [
          ],
        ),
      ),
    );
  }
}

class Main extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 430,
          height: 932,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 3,
                top: 242,
                child: Container(
                  width: 424,
                  height: 169,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 1, color: Color(0xFF052573)),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 5,
                top: 430,
                child: Container(
                  width: 419,
                  height: 372,
                  decoration: ShapeDecoration(
                    color: Color(0xFFBBDEFB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 374,
                top: 61,
                child: Container(
                  width: 37,
                  height: 37,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/37x37"),
                      fit: BoxFit.fill,
                    ),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 323,
                top: 61,
                child: Container(
                  width: 37,
                  height: 37,
                  decoration: ShapeDecoration(
                    color: Color(0xFFD9D9D9),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 272,
                top: 61,
                child: Container(
                  width: 37,
                  height: 37,
                  decoration: ShapeDecoration(
                    color: Color(0xFFEDEDED),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 61,
                child: Container(
                  width: 37,
                  height: 37,
                  decoration: ShapeDecoration(
                    color: Color(0xFFEDEDED),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 99,
                top: 171,
                child: SizedBox(
                  width: 339,
                  height: 44,
                  child: Text(
                    '나만의 캘린더',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 37,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w700,
                      height: 0.03,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 65,
                top: 455,
                child: SizedBox(
                  width: 288,
                  height: 41,
                  child: Text(
                    'My Schedule',
                    style: TextStyle(
                      color: Color(0xFF052573),
                      fontSize: 33,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w700,
                      height: 0.04,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 15,
                top: 246,
                child: SizedBox(
                  width: 288,
                  height: 34,
                  child: Text(
                    '2024년 11월 11일 월요일',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'OdorMeanChey',
                      fontWeight: FontWeight.w400,
                      height: 0.18,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 286,
                child: Container(
                  width: 394,
                  height: 50,
                  decoration: ShapeDecoration(
                    color: Color(0xFFBBDEFB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 367,
                top: 292,
                child: Container(
                  width: 37,
                  height: 37,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 71,
                top: 291,
                child: SizedBox(
                  width: 280,
                  height: 32,
                  child: Text(
                    '오늘 일정 : 5건',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Numans',
                      fontWeight: FontWeight.w400,
                      height: 0.18,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 293,
                child: Container(
                  width: 37,
                  height: 37,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/37x37"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 518,
                child: SizedBox(
                  width: 118,
                  height: 34,
                  child: Text(
                    'TODAY (11/11)',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w400,
                      height: 0.20,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 627,
                child: SizedBox(
                  width: 320,
                  height: 34,
                  child: Text(
                    '13:00-15:00 객지프',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w400,
                      height: 0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 592,
                child: SizedBox(
                  width: 320,
                  height: 34,
                  child: Text(
                    '11:00-13:00 ACT ',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w400,
                      height: 0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 557,
                child: SizedBox(
                  width: 320,
                  height: 34,
                  child: Text(
                    '10:00-11:00 프밍언',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w400,
                      height: 0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 662,
                child: SizedBox(
                  width: 320,
                  height: 34,
                  child: Text(
                    '17:30-20:00 알바',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w400,
                      height: 0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 59,
                top: 697,
                child: SizedBox(
                  width: 320,
                  height: 34,
                  child: Text(
                    '21:00-22:00 동아리 연습',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Pretendard',
                      fontWeight: FontWeight.w400,
                      height: 0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 567,
                child: Container(
                  width: 18,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7D5D0),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 603,
                child: Container(
                  width: 18,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7D5D0),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 638,
                child: Container(
                  width: 18,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7D5D0),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 707,
                child: Container(
                  width: 18,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7D5D0),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 673,
                child: Container(
                  width: 18,
                  height: 18,
                  decoration: ShapeDecoration(
                    color: Color(0xFFE7D5D0),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 628,
                child: Container(
                  width: 143,
                  height: 1,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 32,
                top: 628,
                child: Container(
                  width: 354,
                  height: 1,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 32,
                top: 593,
                child: Container(
                  width: 354,
                  height: 1,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 32,
                top: 733,
                child: Container(
                  width: 354,
                  height: 1,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 32,
                top: 698,
                child: Container(
                  width: 354,
                  height: 1,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 32,
                top: 663,
                child: Container(
                  width: 354,
                  height: 1,
                  decoration: BoxDecoration(color: Color(0xFFD9D9D9)),
                ),
              ),
              Positioned(
                left: 23,
                top: 866,
                child: Container(width: 39, height: 39),
              ),
              Positioned(
                left: 279,
                top: 68,
                child: Container(
                  width: 23,
                  height: 23,
                  padding: const EdgeInsets.all(2.88),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 330,
                top: 68,
                child: Container(
                  width: 23,
                  height: 23,
                  padding: const EdgeInsets.only(
                    top: 1.92,
                    left: 2.88,
                    right: 2.88,
                    bottom: 0.96,
                  ),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 30,
                top: 70,
                child: Container(
                  width: 23,
                  height: 23,
                  padding: const EdgeInsets.symmetric(horizontal: 3.83, vertical: 2.88),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 374,
                top: 298,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.all(5),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 346,
                child: Container(
                  width: 394,
                  height: 50,
                  decoration: ShapeDecoration(
                    color: Color(0xFFBBDEFB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 367,
                top: 352,
                child: Container(
                  width: 37,
                  height: 37,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 73,
                top: 352,
                child: SizedBox(
                  width: 280,
                  height: 32,
                  child: Text(
                    '빼빼로데이 / 가래떡데이',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 15,
                      fontFamily: 'Numans',
                      fontWeight: FontWeight.w400,
                      height: 0.18,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 352,
                child: Container(
                  width: 37,
                  height: 37,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/37x37"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 374,
                top: 358,
                child: Container(
                  width: 24,
                  height: 24,
                  padding: const EdgeInsets.all(5),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [                    
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 870,
                child: Container(
                  width: 39,
                  height: 39,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 855,
                child: Container(
                  width: 430,
                  height: 77,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(30),
                        bottomRight: Radius.circular(30),
                      ),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 10,
                        offset: Offset(0, -3),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 873,
                child: Container(
                  width: 27,
                  height: 27,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: FlutterLogo(),
                ),
              ),
              Positioned(
                left: 31,
                top: 862,
                child: Opacity(
                  opacity: 0.30,
                  child: Container(
                    width: 50,
                    height: 50,
                    decoration: ShapeDecoration(
                      color: Color(0xFF052573),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 188,
                top: 839,
                child: Container(
                  width: 53,
                  height: 53,
                  decoration: ShapeDecoration(
                    color: Color(0xFF052573),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 367,
                top: 876,
                child: Container(
                  width: 27,
                  height: 27,
                  padding: const EdgeInsets.symmetric(vertical: 1.69),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 188,
                top: 839,
                child: Container(
                  width: 53,
                  height: 51,
                  padding: const EdgeInsets.only(
                    top: 10.62,
                    left: 11.04,
                    right: 11.04,
                    bottom: 10.63,
                  ),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 290,
                top: 875,
                child: Container(
                  width: 27,
                  height: 27,
                  padding: const EdgeInsets.only(
                    top: 3.38,
                    left: 2.25,
                    right: 2.25,
                    bottom: 2.25,
                  ),
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 130,
                top: 875,
                child: Container(
                  width: 27,
                  height: 27,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 454,
                child: Container(
                  width: 32,
                  height: 36,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://via.placeholder.com/32x36"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}